import Foundation

struct PeriodicElement {
    let name: String
    let symbol: String
    let atomicNumber: Int
    let atomicWeight: String
    let facts: String
}

/// Transcribed from periodic_table_uploader.py's ELEMENTS table. Electron
/// configuration is omitted — the original script never actually renders it.
enum PeriodicElements {
    static let all: [PeriodicElement] = [
        PeriodicElement(name: "Hydrogen", symbol: "H", atomicNumber: 1, atomicWeight: "1.008", facts: "Most abundant element in the universe. Makes up 75% of all normal matter. Essential for life."),
        PeriodicElement(name: "Helium", symbol: "He", atomicNumber: 2, atomicWeight: "4.003", facts: "Second most abundant element. Has lowest melting point. Used in balloons and diving."),
        PeriodicElement(name: "Lithium", symbol: "Li", atomicNumber: 3, atomicWeight: "6.941", facts: "Lightest metal. Used in batteries and psychiatric medications. Highly reactive."),
        PeriodicElement(name: "Beryllium", symbol: "Be", atomicNumber: 4, atomicWeight: "9.012", facts: "Lightweight and strong. Used in aerospace. Toxic if inhaled. Found in emeralds."),
        PeriodicElement(name: "Boron", symbol: "B", atomicNumber: 5, atomicWeight: "10.811", facts: "Used in glass and ceramics. Essential for plant growth. Forms boron nitride."),
        PeriodicElement(name: "Carbon", symbol: "C", atomicNumber: 6, atomicWeight: "12.011", facts: "Backbone of all life. Forms diamonds and graphite. Essential for organic chemistry."),
        PeriodicElement(name: "Nitrogen", symbol: "N", atomicNumber: 7, atomicWeight: "14.007", facts: "Makes up 78% of atmosphere. Essential for proteins. Used in fertilizers and explosives."),
        PeriodicElement(name: "Oxygen", symbol: "O", atomicNumber: 8, atomicWeight: "15.999", facts: "Essential for respiration. Third most abundant element. Forms water and oxides."),
        PeriodicElement(name: "Fluorine", symbol: "F", atomicNumber: 9, atomicWeight: "18.998", facts: "Most electronegative element. Extremely reactive. Used in toothpaste and refrigerants."),
        PeriodicElement(name: "Neon", symbol: "Ne", atomicNumber: 10, atomicWeight: "20.180", facts: "Glows red in neon lights. Second lightest noble gas. Used in signage."),
        PeriodicElement(name: "Sodium", symbol: "Na", atomicNumber: 11, atomicWeight: "22.990", facts: "Essential for nerve function. Highly reactive with water. Makes up table salt."),
        PeriodicElement(name: "Magnesium", symbol: "Mg", atomicNumber: 12, atomicWeight: "24.305", facts: "Essential for photosynthesis. Lightweight metal. Used in alloys and supplements."),
        PeriodicElement(name: "Aluminium", symbol: "Al", atomicNumber: 13, atomicWeight: "26.982", facts: "Most abundant metal in Earth's crust. Lightweight and durable. Used in aircraft and foil."),
        PeriodicElement(name: "Silicon", symbol: "Si", atomicNumber: 14, atomicWeight: "28.086", facts: "Second most abundant element in crust. Used in semiconductors and glass."),
        PeriodicElement(name: "Phosphorus", symbol: "P", atomicNumber: 15, atomicWeight: "30.974", facts: "Essential for DNA and energy. White phosphorus glows. Used in fertilizers."),
        PeriodicElement(name: "Sulfur", symbol: "S", atomicNumber: 16, atomicWeight: "32.065", facts: "Bright yellow solid. Essential for proteins. Used in matches and vulcanization."),
        PeriodicElement(name: "Chlorine", symbol: "Cl", atomicNumber: 17, atomicWeight: "35.453", facts: "Toxic greenish gas. Disinfects water. Essential for stomach acid."),
        PeriodicElement(name: "Argon", symbol: "Ar", atomicNumber: 18, atomicWeight: "39.948", facts: "Third most abundant in atmosphere. Inert noble gas. Used in welding and lighting."),
        PeriodicElement(name: "Potassium", symbol: "K", atomicNumber: 19, atomicWeight: "39.098", facts: "Essential for heart function. Violently reactive with water. Softer than sodium."),
        PeriodicElement(name: "Calcium", symbol: "Ca", atomicNumber: 20, atomicWeight: "40.078", facts: "Essential for bones and teeth. Most abundant metal in human body."),
        PeriodicElement(name: "Scandium", symbol: "Sc", atomicNumber: 21, atomicWeight: "44.956", facts: "Rare transition metal. Lightweight and strong. Used in aerospace alloys."),
        PeriodicElement(name: "Titanium", symbol: "Ti", atomicNumber: 22, atomicWeight: "47.867", facts: "Extremely strong and lightweight. Corrosion resistant. Used in aircraft and implants."),
        PeriodicElement(name: "Vanadium", symbol: "V", atomicNumber: 23, atomicWeight: "50.942", facts: "Hard transition metal. Used in steel alloys. Found in some organisms."),
        PeriodicElement(name: "Chromium", symbol: "Cr", atomicNumber: 24, atomicWeight: "51.996", facts: "Shiny and resistant to corrosion. Used in stainless steel and plating."),
        PeriodicElement(name: "Manganese", symbol: "Mn", atomicNumber: 25, atomicWeight: "54.938", facts: "Essential trace mineral. Used in steel production. Found in batteries."),
        PeriodicElement(name: "Iron", symbol: "Fe", atomicNumber: 26, atomicWeight: "55.845", facts: "Fourth most abundant in crust. Essential for blood. Most used metal globally."),
        PeriodicElement(name: "Cobalt", symbol: "Co", atomicNumber: 27, atomicWeight: "58.933", facts: "Radioactive. Used in nuclear medicine. Creates blue pigment."),
        PeriodicElement(name: "Nickel", symbol: "Ni", atomicNumber: 28, atomicWeight: "58.693", facts: "Used in coins and alloys. Magnetic properties. Ferromagnetic metal."),
        PeriodicElement(name: "Copper", symbol: "Cu", atomicNumber: 29, atomicWeight: "63.546", facts: "Excellent conductor. One of first metals used. Used in wiring and coins."),
        PeriodicElement(name: "Zinc", symbol: "Zn", atomicNumber: 30, atomicWeight: "65.380", facts: "Essential mineral. Used in galvanizing. Component of brass."),
        PeriodicElement(name: "Gallium", symbol: "Ga", atomicNumber: 31, atomicWeight: "69.723", facts: "Melts in hot water. Semiconductor material. Used in integrated circuits."),
        PeriodicElement(name: "Germanium", symbol: "Ge", atomicNumber: 32, atomicWeight: "72.640", facts: "Semiconductor. Used in infrared optics. Pure germanium is a brittle solid."),
        PeriodicElement(name: "Arsenic", symbol: "As", atomicNumber: 33, atomicWeight: "74.922", facts: "Highly toxic. Used in semiconductors. Found in some pesticides."),
        PeriodicElement(name: "Selenium", symbol: "Se", atomicNumber: 34, atomicWeight: "78.960", facts: "Essential trace mineral. Photosensitive. Used in photocopiers."),
        PeriodicElement(name: "Bromine", symbol: "Br", atomicNumber: 35, atomicWeight: "79.904", facts: "Only liquid nonmetal. Toxic fumes. Used in flame retardants."),
        PeriodicElement(name: "Krypton", symbol: "Kr", atomicNumber: 36, atomicWeight: "83.798", facts: "Noble gas. Used in lighting. Found in Earth's atmosphere."),
        PeriodicElement(name: "Rubidium", symbol: "Rb", atomicNumber: 37, atomicWeight: "85.468", facts: "Highly reactive alkali metal. Soft and silvery. Used in vacuum tubes."),
        PeriodicElement(name: "Strontium", symbol: "Sr", atomicNumber: 38, atomicWeight: "87.620", facts: "Creates red flames. Used in fireworks. Important for bone health."),
        PeriodicElement(name: "Yttrium", symbol: "Y", atomicNumber: 39, atomicWeight: "88.906", facts: "Used in lasers. Component of phosphors. Rare earth element."),
        PeriodicElement(name: "Zirconium", symbol: "Zr", atomicNumber: 40, atomicWeight: "91.224", facts: "Highly resistant to corrosion. Used in nuclear reactors. Found in gemstones."),
        PeriodicElement(name: "Niobium", symbol: "Nb", atomicNumber: 41, atomicWeight: "92.906", facts: "Used in superconductors. High melting point. Found in alloys."),
        PeriodicElement(name: "Molybdenum", symbol: "Mo", atomicNumber: 42, atomicWeight: "95.940", facts: "Used in steel alloys. Essential for enzymes. High melting point."),
        PeriodicElement(name: "Technetium", symbol: "Tc", atomicNumber: 43, atomicWeight: "98", facts: "Artificially created. Radioactive. Used in medical imaging."),
        PeriodicElement(name: "Ruthenium", symbol: "Ru", atomicNumber: 44, atomicWeight: "101.070", facts: "Rare transition metal. Resistant to corrosion. Used as catalyst."),
        PeriodicElement(name: "Rhodium", symbol: "Rh", atomicNumber: 45, atomicWeight: "102.906", facts: "Highly expensive precious metal. Used in catalytic converters."),
        PeriodicElement(name: "Palladium", symbol: "Pd", atomicNumber: 46, atomicWeight: "106.420", facts: "Precious metal. Used in catalysts. Can absorb hydrogen gas."),
        PeriodicElement(name: "Silver", symbol: "Ag", atomicNumber: 47, atomicWeight: "107.868", facts: "Best electrical conductor. Used in jewelry and electronics. Highly reflective."),
        PeriodicElement(name: "Cadmium", symbol: "Cd", atomicNumber: 48, atomicWeight: "112.411", facts: "Toxic heavy metal. Used in batteries. Carcinogenic if inhaled."),
        PeriodicElement(name: "Indium", symbol: "In", atomicNumber: 49, atomicWeight: "114.818", facts: "Soft silvery metal. Used in touch screens. Semiconductor material."),
        PeriodicElement(name: "Tin", symbol: "Sn", atomicNumber: 50, atomicWeight: "118.710", facts: "Used in solder. Forms tin oxide. Bronze is copper-tin alloy."),
        PeriodicElement(name: "Antimony", symbol: "Sb", atomicNumber: 51, atomicWeight: "121.760", facts: "Brittle metal-like element. Used in flame retardants."),
        PeriodicElement(name: "Tellurium", symbol: "Te", atomicNumber: 52, atomicWeight: "127.600", facts: "Semiconductor element. Rare in nature. Used in solar cells."),
        PeriodicElement(name: "Iodine", symbol: "I", atomicNumber: 53, atomicWeight: "126.904", facts: "Essential for thyroid. Purple crystalline solid. Used as disinfectant."),
        PeriodicElement(name: "Xenon", symbol: "Xe", atomicNumber: 54, atomicWeight: "131.293", facts: "Noble gas. Dense atmosphere. Used in headlights and anesthesia."),
        PeriodicElement(name: "Cesium", symbol: "Cs", atomicNumber: 55, atomicWeight: "132.905", facts: "Soft alkali metal. Used in atomic clocks. One of rarest elements."),
        PeriodicElement(name: "Barium", symbol: "Ba", atomicNumber: 56, atomicWeight: "137.327", facts: "Used in X-ray imaging. Creates green flames. Important for density."),
        PeriodicElement(name: "Lanthanum", symbol: "La", atomicNumber: 57, atomicWeight: "138.905", facts: "Rare earth element. Used in optical lenses. Lanthanide series starter."),
        PeriodicElement(name: "Cerium", symbol: "Ce", atomicNumber: 58, atomicWeight: "140.116", facts: "Most abundant rare earth. Used in catalytic converters."),
        PeriodicElement(name: "Praseodymium", symbol: "Pr", atomicNumber: 59, atomicWeight: "140.908", facts: "Rare earth metal. Creates yellow color. Used in magnets."),
        PeriodicElement(name: "Neodymium", symbol: "Nd", atomicNumber: 60, atomicWeight: "144.242", facts: "Creates powerful permanent magnets. Used in wind turbines."),
        PeriodicElement(name: "Promethium", symbol: "Pm", atomicNumber: 61, atomicWeight: "145", facts: "Artificially created. Radioactive. Used in luminous paint."),
        PeriodicElement(name: "Samarium", symbol: "Sm", atomicNumber: 62, atomicWeight: "150.360", facts: "Rare earth metal. Used in permanent magnets. Samarium cobalt alloys."),
        PeriodicElement(name: "Europium", symbol: "Eu", atomicNumber: 63, atomicWeight: "151.964", facts: "Creates red phosphor. Used in euro banknote security features."),
        PeriodicElement(name: "Gadolinium", symbol: "Gd", atomicNumber: 64, atomicWeight: "157.250", facts: "Used in MRI contrast agents. Highly magnetic element."),
        PeriodicElement(name: "Terbium", symbol: "Tb", atomicNumber: 65, atomicWeight: "158.925", facts: "Rare earth element. Used in green phosphor. Magnetic properties."),
        PeriodicElement(name: "Dysprosium", symbol: "Dy", atomicNumber: 66, atomicWeight: "162.500", facts: "Rare earth metal. Used in permanent magnets. Highly magnetic."),
        PeriodicElement(name: "Holmium", symbol: "Ho", atomicNumber: 67, atomicWeight: "164.930", facts: "Rare earth element. Used in lasers and magnets."),
        PeriodicElement(name: "Erbium", symbol: "Er", atomicNumber: 68, atomicWeight: "167.259", facts: "Pink rare earth element. Used in fiber optic amplifiers."),
        PeriodicElement(name: "Thulium", symbol: "Tm", atomicNumber: 69, atomicWeight: "168.934", facts: "Rarest naturally occurring rare earth. Used in portable X-ray devices."),
        PeriodicElement(name: "Ytterbium", symbol: "Yb", atomicNumber: 70, atomicWeight: "173.040", facts: "Rare earth element. Used in atomic clocks. Found in monazite sand."),
        PeriodicElement(name: "Lutetium", symbol: "Lu", atomicNumber: 71, atomicWeight: "174.967", facts: "Heaviest rare earth. Used in PET scanners. Last lanthanide."),
        PeriodicElement(name: "Hafnium", symbol: "Hf", atomicNumber: 72, atomicWeight: "178.492", facts: "Used in nuclear reactors. High melting point. Zirconium analog."),
        PeriodicElement(name: "Tantalum", symbol: "Ta", atomicNumber: 73, atomicWeight: "180.948", facts: "Highly resistant to corrosion. Used in capacitors. Surgical implants."),
        PeriodicElement(name: "Tungsten", symbol: "W", atomicNumber: 74, atomicWeight: "183.840", facts: "Highest melting point of all metals. Used in light bulb filaments."),
        PeriodicElement(name: "Rhenium", symbol: "Re", atomicNumber: 75, atomicWeight: "186.207", facts: "Very rare element. High melting point. Used in superalloys."),
        PeriodicElement(name: "Osmium", symbol: "Os", atomicNumber: 76, atomicWeight: "190.233", facts: "Densest element. Toxic. Used in fountain pen nibs."),
        PeriodicElement(name: "Iridium", symbol: "Ir", atomicNumber: 77, atomicWeight: "192.217", facts: "Highly resistant to corrosion. Used in platinum alloys. Extremely hard."),
        PeriodicElement(name: "Platinum", symbol: "Pt", atomicNumber: 78, atomicWeight: "195.084", facts: "Precious metal. Excellent catalyst. Resistant to corrosion."),
        PeriodicElement(name: "Gold", symbol: "Au", atomicNumber: 79, atomicWeight: "196.967", facts: "Precious and valuable. Excellent conductor. Used in jewelry."),
        PeriodicElement(name: "Mercury", symbol: "Hg", atomicNumber: 80, atomicWeight: "200.592", facts: "Only liquid metal. Highly toxic. Used in thermometers."),
        PeriodicElement(name: "Thallium", symbol: "Tl", atomicNumber: 81, atomicWeight: "204.383", facts: "Soft metal. Highly toxic. Used in rodent poisons."),
        PeriodicElement(name: "Lead", symbol: "Pb", atomicNumber: 82, atomicWeight: "207.200", facts: "Soft heavy metal. Toxic. Used in batteries and shielding."),
        PeriodicElement(name: "Bismuth", symbol: "Bi", atomicNumber: 83, atomicWeight: "208.980", facts: "Creates rainbow crystals. Expands when solidifying. Used in cosmetics."),
        PeriodicElement(name: "Polonium", symbol: "Po", atomicNumber: 84, atomicWeight: "209", facts: "Highly radioactive. Extremely toxic. Discovered by Marie Curie."),
        PeriodicElement(name: "Astatine", symbol: "At", atomicNumber: 85, atomicWeight: "210", facts: "Extremely rare. Highly radioactive. Rarest naturally occurring element."),
        PeriodicElement(name: "Radon", symbol: "Rn", atomicNumber: 86, atomicWeight: "222", facts: "Radioactive noble gas. Colorless and odorless. Health hazard in homes."),
        PeriodicElement(name: "Francium", symbol: "Fr", atomicNumber: 87, atomicWeight: "223", facts: "Extremely rare and radioactive. Heaviest alkali metal. Highly reactive."),
        PeriodicElement(name: "Radium", symbol: "Ra", atomicNumber: 88, atomicWeight: "226", facts: "Radioactive. Glows in dark. Used historically in watch paint."),
        PeriodicElement(name: "Actinium", symbol: "Ac", atomicNumber: 89, atomicWeight: "227", facts: "Radioactive. Starts actinide series. Used in cancer radiotherapy."),
        PeriodicElement(name: "Thorium", symbol: "Th", atomicNumber: 90, atomicWeight: "232.038", facts: "Radioactive. More abundant than uranium. Used in nuclear fuel."),
        PeriodicElement(name: "Protactinium", symbol: "Pa", atomicNumber: 91, atomicWeight: "231.036", facts: "Highly radioactive. Extremely rare. Toxic element."),
        PeriodicElement(name: "Uranium", symbol: "U", atomicNumber: 92, atomicWeight: "238.029", facts: "Heaviest natural element. Nuclear fuel. Highly radioactive."),
        PeriodicElement(name: "Neptunium", symbol: "Np", atomicNumber: 93, atomicWeight: "237", facts: "Artificially created. Radioactive. Named after planet Neptune."),
        PeriodicElement(name: "Plutonium", symbol: "Pu", atomicNumber: 94, atomicWeight: "244", facts: "Artificially created. Used in nuclear weapons and power."),
        PeriodicElement(name: "Americium", symbol: "Am", atomicNumber: 95, atomicWeight: "243", facts: "Radioactive. Used in smoke detectors. Named after America."),
        PeriodicElement(name: "Curium", symbol: "Cm", atomicNumber: 96, atomicWeight: "247", facts: "Named after Marie Curie. Radioactive. Used in space probes."),
        PeriodicElement(name: "Berkelium", symbol: "Bk", atomicNumber: 97, atomicWeight: "247", facts: "Radioactive. Extremely rare. Named after Berkeley."),
        PeriodicElement(name: "Californium", symbol: "Cf", atomicNumber: 98, atomicWeight: "251", facts: "Radioactive. Named after California. Used in nuclear medicine."),
        PeriodicElement(name: "Einsteinium", symbol: "Es", atomicNumber: 99, atomicWeight: "252", facts: "Radioactive. Named after Einstein. Discovered in thermonuclear tests."),
        PeriodicElement(name: "Fermium", symbol: "Fm", atomicNumber: 100, atomicWeight: "257", facts: "Radioactive. Named after Enrico Fermi. Discovered in 1952."),
        PeriodicElement(name: "Mendelevium", symbol: "Md", atomicNumber: 101, atomicWeight: "258", facts: "Radioactive. Named after Mendeleev. Extremely rare."),
        PeriodicElement(name: "Nobelium", symbol: "No", atomicNumber: 102, atomicWeight: "259", facts: "Radioactive. Named after Nobel Prize. Discovered in 1966."),
        PeriodicElement(name: "Lawrencium", symbol: "Lr", atomicNumber: 103, atomicWeight: "266", facts: "Radioactive. Named after Lawrence Lab. Last actinide."),
        PeriodicElement(name: "Rutherfordium", symbol: "Rf", atomicNumber: 104, atomicWeight: "267", facts: "Synthetic element. Extremely unstable. Named after Rutherford."),
        PeriodicElement(name: "Dubnium", symbol: "Db", atomicNumber: 105, atomicWeight: "268", facts: "Synthetic element. Highly unstable. Named after Dubna."),
        PeriodicElement(name: "Seaborgium", symbol: "Sg", atomicNumber: 106, atomicWeight: "271", facts: "Synthetic element. Extremely rare. Named after Seaborg."),
        PeriodicElement(name: "Bohrium", symbol: "Bh", atomicNumber: 107, atomicWeight: "272", facts: "Synthetic element. Extremely unstable. Named after Bohr."),
        PeriodicElement(name: "Hassium", symbol: "Hs", atomicNumber: 108, atomicWeight: "270", facts: "Synthetic element. Radioactive. Named after Hesse state."),
        PeriodicElement(name: "Meitnerium", symbol: "Mt", atomicNumber: 109, atomicWeight: "278", facts: "Synthetic element. Named after Lise Meitner. Extremely rare."),
        PeriodicElement(name: "Darmstadtium", symbol: "Ds", atomicNumber: 110, atomicWeight: "281", facts: "Synthetic element. Named after Darmstadt. Highly unstable."),
        PeriodicElement(name: "Roentgenium", symbol: "Rg", atomicNumber: 111, atomicWeight: "280", facts: "Synthetic element. Named after Roentgen. Radioactive."),
        PeriodicElement(name: "Copernicium", symbol: "Cn", atomicNumber: 112, atomicWeight: "285", facts: "Synthetic element. May be liquid. Named after Copernicus."),
        PeriodicElement(name: "Nihonium", symbol: "Nh", atomicNumber: 113, atomicWeight: "286", facts: "Synthetic element. Named after Japan. Recently confirmed."),
        PeriodicElement(name: "Flerovium", symbol: "Fl", atomicNumber: 114, atomicWeight: "289", facts: "Synthetic element. Named after Flerov Lab. Superheavy element."),
        PeriodicElement(name: "Moscovium", symbol: "Mc", atomicNumber: 115, atomicWeight: "290", facts: "Synthetic element. Named after Moscow. Extremely rare."),
        PeriodicElement(name: "Livermorium", symbol: "Lv", atomicNumber: 116, atomicWeight: "293", facts: "Synthetic element. Named after Livermore. Highly unstable."),
        PeriodicElement(name: "Tennessine", symbol: "Ts", atomicNumber: 117, atomicWeight: "294", facts: "Synthetic element. Named after Tennessee. Recently named."),
        PeriodicElement(name: "Oganesson", symbol: "Og", atomicNumber: 118, atomicWeight: "294", facts: "Heaviest element. Synthetic. Named after Yuri Oganessian."),
    ]
}
